### ISSUE TITLE
make captcha stronger

### ISSUE THREAD

**Issue by KOLANICH** [iionly/Elgg_1.8_captcha#1]
hi
your captcha seems to be weak because of the
1 limited set of backgrounds
2 though the symbols are black and bg is black it is possible to remove bg using hough transform + erode
3 но rotations
4 no nonlinear distortion
try to use http://captcha.ru/kcaptcha.zip

**Comment by iionly** [comment]
Thanks for the suggestion. I might release a kcaptcha based captcha plugin when I've a bit time to spare. This might take a while though, so I can't promise. The main reason for coding the captcha plugin for Elgg 1.8 (using the captcha algorithm used in former Elgg versions) was to have a captcha plugin for testing another plugin I'm working on that makes use of the captchas. Still working on that one...
